/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:412b9772-de6b-4436-acc4-60e5e1ce6e04",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_b64H0PXqL",
    "aws_user_pools_web_client_id": "7nn74oh41dueehner7coh9iua7",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "geo": {
        "amazon_location_service": {
            "region": "us-west-2",
            "maps": {
                "items": {
                    "mapc8af1b3f-dev": {
                        "style": "VectorEsriStreets"
                    }
                },
                "default": "mapc8af1b3f-dev"
            },
            "search_indices": {
                "items": [
                    "placeindex31e3e26b-dev"
                ],
                "default": "placeindex31e3e26b-dev"
            }
        }
    }
};


export default awsmobile;
